apiVersion: v1
kind: Service
metadata:
  name: namegen-service
  labels:
    app: namegen-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: namegen-app